=== nuts-foundation/nuts-node/discovery/service-definition-schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Service Definition",
  "type": "object",
  "properties": {
    "id": {
      "type": "string",
      "minLength": 1
    },
    "endpoint": {
      "type": "string",
      "minLength": 1
    },
    "presentation_max_validity": {
      "type": "integer",
      "minimum": 1
    },
    "presentation_definition": {
      "$ref": "http://identity.foundation/presentation-exchange/schemas/presentation-definition.json"
    }
  },
  "required": [
    "id",
    "endpoint",
    "presentation_max_validity",
    "presentation_definition"
  ]
}

=== nuts-foundation/nuts-node/e2e-tests/oauth-flow/didx509/discovery.json
{
  "id": "e2e-test",
  "endpoint": "http://nodeA-backend:8080/discovery/e2e-test",
  "presentation_max_validity": 36000,
  "presentation_definition": {
    "id": "pd_e2e_test",
    "format": {
      "jwt_vc": {
        "alg": [
          "PS256"
        ]
      },
      "jwt_vp": {
        "alg": [
          "PS256"
        ]
      }
    },
    "input_descriptors": [
      {
        "id": "id_x509credential",
        "constraints": {
          "fields": [
            {
              "path": [
                "$.type"
              ],
              "filter": {
                "type": "string",
                "const": "X509Credential"
              }
            },
            {
              "path": [
                "$.issuer"
              ],
              "purpose": "Whe can only accept credentials from a trusted issuer",
              "filter": {
                "type": "string",
                "pattern": "^did:x509:0:sha256:szqMaTpnD6GN0aRrT98eV4bhAoOgyItEZVyskYyL_Qc::.*$"
              }
            },
            {
              "id": "organization_name",
              "path": [
                "$.credentialSubject[0].subject.O"
              ],
              "filter": {
                "type": "string"
              }
            },
            {
              "id": "organization_ura",
              "path": [
                "$.credentialSubject[0].san.otherName"
              ],
              "filter": {
                "type": "string",
                "pattern": "^[0-9.]+-\\d+-\\d+-S-(\\d+)-00\\.000-\\d+$"
              }
            },
            {
              "id": "organization_city",
              "path": [
                "$.credentialSubject[0].subject.L"
              ],
              "filter": {
                "type": "string"
              }
            }
          ]
        }
      }
    ]
  }
}

=== nuts-foundation/nuts-node/e2e-tests/clustering/memcached/shared/discovery/definition.json
{
  "id": "e2e-test",
  "endpoint": "http://nodeA-backend:8080/discovery/e2e-test",
  "presentation_max_validity": 36000,
  "presentation_definition": {
    "id": "pd_eoverdracht_dev_care_organization",
    "format": {
      "ldp_vc": {
        "proof_type": [
          "JsonWebSignature2020"
        ]
      }
    },
    "input_descriptors": [
      {
        "id": "id_nuts_care_organization_cred",
        "constraints": {
          "fields": [
            {
              "path": [
                "$.type"
              ],
              "filter": {
                "type": "string",
                "const": "NutsOrganizationCredential"
              }
            },
            {
              "path": [
                "$.credentialSubject.organization.name",
                "$.credentialSubject[0].organization.name"
              ],
              "filter": {
                "type": "string"
              }
            },
            {
              "path": [
                "$.credentialSubject.organization.city",
                "$.credentialSubject[0].organization.city"
              ],
              "filter": {
                "type": "string"
              }
            }
          ]
        }
      }
    ]
  }
}

=== nuts-foundation/nuts-node/discoveryservice/test/duplicate_id/2.json
{
  "id": "urn:nuts.nl:usecase:eOverdrachtDev2023",
  "endpoint": "https://example.com/usecase/eoverdracht_dev",
  "presentation_max_validity": 36000,
  "presentation_definition": {
    "id": "pd_eoverdracht_dev_care_organization",
    "format": {
      "ldp_vc": {
        "proof_type": [
          "JsonWebSignature2020"
        ]
      }
    },
    "input_descriptors": [
      {
        "id": "id_nuts_care_organization_cred",
        "constraints": {
          "fields": [
            {
              "path": [
                "$.type"
              ],
              "filter": {
                "type": "string",
                "const": "NutsOrganizationCredential"
              }
            },
            {
              "path": [
                "$.credentialSubject.organization.name"
              ],
              "filter": {
                "type": "string"
              }
            },
            {
              "path": [
                "$.credentialSubject.organization.city"
              ],
              "filter": {
                "type": "string"
              }
            }
          ]
        }
      }
    ]
  }
}

=== nuts-foundation/nuts-node/e2e-tests/discovery/definitions/definition.json
{
  "id": "dev:eOverdracht2023",
  "endpoint": "https://nodeA/discovery/dev:eOverdracht2023",
  "presentation_max_validity": 2764800,
  "presentation_definition": {
    "id": "dev:eOverdracht2023",
    "format": {
      "ldp_vc": {
        "proof_type": [
          "JsonWebSignature2020"
        ]
      },
      "jwt_vp": {
        "alg": ["ES256"]
      }
    },
    "input_descriptors": [
      {
        "id": "SelfIssued_NutsOrganizationCredential",
        "constraints": {
          "fields": [
            {
              "path": [
                "$.type"
              ],
              "filter": {
                "type": "string",
                "const": "NutsOrganizationCredential"
              }
            },
            {
              "path": [
                "$.credentialSubject.organization.name"
              ],
              "filter": {
                "type": "string"
              }
            },
            {
              "path": [
                "$.credentialSubject.organization.city"
              ],
              "filter": {
                "type": "string"
              }
            }
          ]
        }
      }
    ]
  }
}
